### ISSUE TITLE
command drXX is not understood

### ISSUE THREAD

**Issue by Windsinger1985** [Stationeers-ic/preview#10]
![image](https://github.com/Stationeers-ic/preview/assets/13313548/f6f2cc0b-22f6-47d9-84db-618b92aac87a)

Line 41 states `l r0 dr10 On`

dr10 is a device with the number being referred in this case from r10. and is a valid code in the game.

**Comment by Traineratwot** [comment]
https://stationeers-ic.github.io/preview/eNplj7EOgzAMRH8l8pxKJAFislVdmKpKXVmApIUBkEhgQfn3kqqtgG722e%2FOXqAetAEF3TAbMjLCit4SvRZ341zbPwkveqCgzdzWxoJaQLJMJCzDJDS30TzKKi9tA4qLJBXIZUThA6+ap8BSHmMmEPFInBjHWAopJYVr2ZmgZInEOMXI+29qmLyTt0Zwacd6ah3Jh8mGKPqnqC3wc7Nn58q6MfrwC2gG+1tBV+Hzam9Ew6LakN6%2FALV5Wgk=
