### ISSUE TITLE
and,or functions causing Javascript warnings

### ISSUE THREAD

**Issue by Windsinger1985** [Stationeers-ic/preview#13]
Question,

When i use either `and` or `or` functions, it throws a java error.
`warn: JavaScript use 32bit number, But game use 64 BIT. Can cause problems with big numbers at 32`

To test, use this piece of code.
https://ic10.dev/#eNp9Vdtu2zgQ/ZWB/NgE1c22LLQB0mx2WyyQFMlugQX8osvIZktTWopKmxb5985Q1MVOWiCAoxmeM2cuHP7wirpEL/UWcHf9KYXQD6MgDDd+uFULyKTIWmy3qsRKKASJZWsy07UQbOI4TpZ+EI3OYt8ZzIWCc7LHCbn90dcpWWclalgTJEiC1eTSWDwWklznwSqKNvE6itYTJyqjBaw2/iZebqLlTMkDQUgpR0rWqxNEdqg7ZYDE2RTgD3wQBX6gQ99ABxR8q4QSJt2qNp9ldasgODFd1bLW4MMC3skOt+pQP+ARHbnoqDbwVZg9lMTdSsQGQg5yyISiII8CZckFvXI12iqZt6D9qWg+3BZF1wgsnYTRQ6K0z+B/XRFH8FjVZ+DR48C5wu+ZZMw9pYXvuvaRGe9c7UfGsRnHjDKnqk3OO8x2VOZ2cIWT67Iw4oEiWB07AzpiJFecqsgB6C+yEkfI7ySyyHuDDY3glW1s1e2wTdl8zsBX8GcnJbylQ3VzBnhozCMlbwQZ39C0WL6SOk6H7VfQfw0ZOJEhO5YkIlOlleyzbcER2HKoNYLZZ4rOkG6X/FvOkVUz4poj9xKduAZZ3k1tSMgZfOGRsPKE2vVKnBQ+SDwa//9ujTHFbb+IBhR+owkGSVPdgqhAEVVtD1vNS6t5kkxQsi0g4LN1H33U2tqKLC8mwTfEPisj66y4lK/gg2o6Q9n9zZJ1p1SvmOYj7hVPs3FUsPhl8td1VRHr8sJGAcHsr3PqrusamW3xYGxaa0uxsowD/6pPbpy8iyXhlKMjptuq+k0zeglDYv90WkGthkCJHb8hUHKUyD3f7IHps8trq/iXhjAry6NVMP8/4FXxa/d8TQ3dn/tDDjcb+f4i2I0kxW5P/ecFaMDUsNOIqr+I/rAw+0V2cm1743QPxxMONBY3ciMWPL+7PPLaFsdnjS+sSr43f/WSWHS/qPkEDhp7k70gbtU50WzhXthlNMo6XkW2TzMttoW/0hLbkSm5lryJWdG4XNIXETxk/6GU9VcG6Ywh15+xMJe5xJchdPEW8LHTjcQZZhpBRg07CPzpw+Xv3oZpuGYzlx6f9udMwYDxzrzSTk7rpT+8IKTHl17nTcRfHzVWWf4+a/deeh6ECb2u6/X6zLvJDsiWzXKdxKvEf3oaSNjzjMi7ErrohIH3ddfSOqCQp5Z0DhjZ2ktjsmKP5TPGMmfd+Qnu6Sf9WNWU

**Comment by Traineratwot** [comment]
warn is not error
